'use client';

import { useEffect, useRef, useState } from 'react';
import { Header, SourceBadge } from '../components';

const STORAGE_KEY = 'fire-planner';
const DEFAULTS = [['Rent', 1800], ['Utilities', 250], ['Groceries', 600], ['Transportation', 400], ['Insurance', 300], ['Healthcare', 200], ['Lifestyle', 250], ['Other', 200]];
const emptyExpenses = () => DEFAULTS.map(([name], id) => ({ id, name, amount: 0 }));
const valid = (value) => Number.isFinite(value) && value >= 0;
const validRate = (value) => Number.isFinite(value) && value > 0;
const copy = (items) => items.map((item, id) => ({ ...item, id }));
const money = (value, currency) => value === null ? 'UNAVAILABLE' : new Intl.NumberFormat(currency === 'TRY' ? 'tr-TR' : 'en-US', { style: 'currency', currency, maximumFractionDigits: 0 }).format(value);

export default function FirePage() {
  const [expenses, setExpenses] = useState(emptyExpenses);
  const [income, setIncome] = useState(0);
  const [portfolio, setPortfolio] = useState(0);
  const [currency, setCurrency] = useState('TRY');
  const [rate, setRate] = useState();
  const [rateStatus, setRateStatus] = useState('LOADING RATE...');
  const [usingCache, setUsingCache] = useState(false);
  const [draft, setDraft] = useState();
  const closeRef = useRef(); const recordRef = useRef(); const touchedRef = useRef(false); const currencyRef = useRef('TRY'); const legacyRef = useRef('TRY');

  const persist = (record) => { recordRef.current = record; try { localStorage.setItem(STORAGE_KEY, JSON.stringify(record)); } catch { /* storage may be unavailable */ } };
  const record = (nextExpenses, nextIncome, nextPortfolio, nextRate = rate) => ({ expenses: nextExpenses, income: nextIncome, portfolio: nextPortfolio, inputCurrency: 'TRY', displayCurrency: currencyRef.current, ...(nextRate ? { rate: nextRate.rate, rateBase: nextRate.base, rateQuote: nextRate.quote, rateDate: nextRate.date, rateFetchedAt: nextRate.fetchedAt, rateSource: nextRate.source } : {}) });
  const applyRate = (nextRate, cached = false) => {
    setRate(nextRate); setUsingCache(cached); setRateStatus(cached ? 'USING CACHED RATE' : 'RATE LIVE');
    if (legacyRef.current === 'USD') { const nextExpenses = copy(recordRef.current?.expenses || expenses).map((item) => ({ ...item, amount: item.amount * nextRate.rate })); const nextIncome = (recordRef.current?.income ?? income) * nextRate.rate; const nextPortfolio = (recordRef.current?.portfolio ?? portfolio) * nextRate.rate; legacyRef.current = 'TRY'; setExpenses(nextExpenses); setIncome(nextIncome); setPortfolio(nextPortfolio); persist(record(nextExpenses, nextIncome, nextPortfolio, nextRate)); }
    else if (!recordRef.current && !touchedRef.current) { const nextExpenses = copy(DEFAULTS.map(([name, amount], id) => ({ id, name, amount: amount * nextRate.rate }))); const nextIncome = 7000 * nextRate.rate; const nextPortfolio = 100000 * nextRate.rate; setExpenses(nextExpenses); setIncome(nextIncome); setPortfolio(nextPortfolio); persist(record(nextExpenses, nextIncome, nextPortfolio, nextRate)); }
    else persist(record(recordRef.current?.expenses || expenses, recordRef.current?.income ?? income, recordRef.current?.portfolio ?? portfolio, nextRate));
  };
  const fetchRate = async () => { setRateStatus('LOADING RATE...'); try { const response = await fetch('/api/exchange-rate', { cache: 'no-store' }); const payload = await response.json(); if (!response.ok || payload.base !== 'USD' || payload.quote !== 'TRY' || !validRate(Number(payload.rate))) throw Error('Invalid rate'); applyRate({ ...payload, rate: Number(payload.rate) }); } catch { const cached = recordRef.current?.rate && validRate(Number(recordRef.current.rate)) ? { rate: Number(recordRef.current.rate), base: recordRef.current.rateBase || 'USD', quote: recordRef.current.rateQuote || 'TRY', date: recordRef.current.rateDate, fetchedAt: recordRef.current.rateFetchedAt, source: recordRef.current.rateSource } : undefined; if (cached) applyRate(cached, true); else setRateStatus('RATE UNAVAILABLE'); } };

  useEffect(() => { try { const parsed = JSON.parse(localStorage.getItem(STORAGE_KEY) || 'null'); const validExpenses = Array.isArray(parsed?.expenses) && parsed.expenses.every((item) => typeof item?.name === 'string' && item.name.trim() && valid(Number(item.amount))); if (parsed && validExpenses && valid(Number(parsed.income)) && valid(Number(parsed.portfolio))) { const saved = copy(parsed.expenses.map((item) => ({ name: item.name.trim(), amount: Number(item.amount) }))); const savedCurrency = parsed.displayCurrency === 'USD' || parsed.inputCurrency === 'USD' ? 'USD' : 'TRY'; legacyRef.current = parsed.inputCurrency === 'USD' && !parsed.displayCurrency ? 'USD' : 'TRY'; currencyRef.current = savedCurrency; setExpenses(saved); setIncome(Number(parsed.income)); setPortfolio(Number(parsed.portfolio)); setCurrency(savedCurrency); recordRef.current = { ...parsed, expenses: saved }; if (legacyRef.current === 'TRY' && validRate(Number(parsed.rate))) setRate({ rate: Number(parsed.rate), base: parsed.rateBase || 'USD', quote: parsed.rateQuote || 'TRY', date: parsed.rateDate, fetchedAt: parsed.rateFetchedAt, source: parsed.rateSource }); } } catch { recordRef.current = undefined; } fetchRate(); }, []);

  const factor = currency === 'USD' ? 1 / (rate?.rate || 1) : 1; const ready = currency === 'TRY' || validRate(rate?.rate); const toTry = (value) => currency === 'USD' ? value * (rate?.rate || 0) : value;
  const updateProfile = (key, value) => { touchedRef.current = true; const number = Number(value); if (!valid(number) || (currency === 'USD' && !validRate(rate?.rate))) return; const next = toTry(number); const nextIncome = key === 'income' ? next : income; const nextPortfolio = key === 'portfolio' ? next : portfolio; if (key === 'income') setIncome(next); else setPortfolio(next); persist(record(expenses, nextIncome, nextPortfolio)); };
  const changeCurrency = (next) => { currencyRef.current = next; setCurrency(next); persist({ ...record(expenses, income, portfolio), displayCurrency: next }); };
  const closeEditor = () => setDraft(); const openEditor = () => { setDraft(copy(expenses)); setTimeout(() => closeRef.current?.focus(), 0); };
  useEffect(() => { if (!draft) return; const handler = (event) => event.key === 'Escape' && closeEditor(); document.addEventListener('keydown', handler); return () => document.removeEventListener('keydown', handler); }, [draft]);
  const updateDraft = (index, changes) => setDraft((current) => current.map((item, i) => i === index ? { ...item, ...changes } : item));
  const updateDraftAmount = (index, value) => { const number = Number(value); if (valid(number) && (currency === 'TRY' || validRate(rate?.rate))) updateDraft(index, { amount: toTry(number) }); };
  const saveExpenses = (event) => { event.preventDefault(); const saved = draft.filter((item) => item.name.trim() && valid(item.amount)).map((item, id) => ({ ...item, id, name: item.name.trim(), amount: item.amount })); touchedRef.current = true; setExpenses(saved); persist(record(saved, income, portfolio)); closeEditor(); };

  const monthlyTry = expenses.reduce((sum, item) => sum + (valid(Number(item.amount)) ? Number(item.amount) : 0), 0); const monthly = ready ? monthlyTry * factor : null; const incomeValue = ready ? income * factor : null; const portfolioValue = ready ? portfolio * factor : null; const surplus = ready ? incomeValue - monthly : null; const annual = ready ? monthly * 12 : null; const target = annual === null ? null : annual * 25; const remaining = target === null ? null : Math.max(0, target - portfolioValue); const progress = target === 0 ? 100 : target === null ? null : Math.min(100, portfolioValue / target * 100); const contribution = surplus === null ? null : surplus * 12;
  const targetTry = monthlyTry * 300; const contributionTry = (income - monthlyTry) * 12; let years = null; if (targetTry <= portfolio) years = 0; else if (targetTry > 0 && portfolio * .07 + contributionTry > 0 && targetTry * .07 + contributionTry > 0) { const result = Math.log((targetTry * .07 + contributionTry) / (portfolio * .07 + contributionTry)) / Math.log(1.07); if (Number.isFinite(result) && result >= 0) years = Math.ceil(result); }
  const projectionReady = ready && [monthly, incomeValue, portfolioValue, surplus, annual, target].every(Number.isFinite); const chartYears = projectionReady ? Math.max(1, Math.min(40, (years === null ? 10 : years + 2))) : 0; const data = projectionReady ? Array.from({ length: chartYears + 1 }, (_, year) => ({ year, value: year === 0 ? portfolioValue : portfolioValue * 1.07 ** year + contribution * ((1.07 ** year - 1) / .07) })) : []; const max = data.length ? Math.max(target, ...data.map((point) => point.value), 1) : 1; const x = (year) => 34 + year / chartYears * 532; const y = (value) => 188 - Math.min(1, Math.max(0, value / max)) * 148; const path = data.map((point) => `${x(point.year).toFixed(1)},${y(point.value).toFixed(1)}`).join(' '); const output = (value) => money(value, currency); const symbol = currency === 'TRY' ? '₺' : '$';
  const projection = <section className="fire-projection" aria-labelledby="projection-title"><div className="projection-head"><div><div className="eyebrow">LONG-RANGE PROJECTION / {currency}</div><h2 id="projection-title">Portfolio path to <em>freedom.</em></h2></div><div aria-live="polite">{!projectionReady ? 'PROJECTION UNAVAILABLE' : years === 0 ? 'FIRE REACHED · TODAY' : `ESTIMATED FIRE · ${new Date().getFullYear() + years}`}</div></div>{projectionReady && <div className="projection-chart"><svg viewBox="0 0 600 220" role="img" aria-labelledby="projection-title projection-description"><title id="projection-description">Projected portfolio compared with the FIRE target.</title><line x1="34" y1={y(target)} x2="566" y2={y(target)} stroke="var(--lime)" strokeDasharray="5 5" /><text x="566" y={Math.max(13, y(target) - 7)} textAnchor="end" fill="var(--lime)" fontSize="10">TARGET {output(target)}</text><polyline points={path} fill="none" stroke="var(--cyan)" strokeWidth="3" /><text x="34" y="207" fill="var(--muted)" fontSize="10">NOW</text><text x="566" y="207" textAnchor="end" fill="var(--muted)" fontSize="10">YEAR {chartYears}</text></svg></div>}</section>;

  return <main className="shell fire-page"><Header active="FIRE" stamp={`FIRE PLANNER / ${currency} VALUES`} /><div className="currency-switcher" role="group" aria-label="Display currency"><span>DISPLAY CURRENCY</span><button type="button" className={currency === 'TRY' ? 'active' : ''} aria-pressed={currency === 'TRY'} onClick={() => changeCurrency('TRY')}>TL</button><button type="button" className={currency === 'USD' ? 'active' : ''} aria-pressed={currency === 'USD'} onClick={() => changeCurrency('USD')}>USD</button></div><section className="fire-hero"><div><div className="eyebrow">FINANCIAL INDEPENDENCE / RETIRE EARLY</div><h1>Find your<br /><em>number.</em></h1><p>A clear view of what your current spending and saving rate could support.</p></div><div className="fire-orbit" aria-hidden="true"><span>4%</span><i /></div></section>
    <section className="profile-strip panel" aria-label="Financial profile"><div><label htmlFor="income">MONTHLY AFTER-TAX INCOME / {currency}</label><div className="profile-input"><span>{symbol}</span><input id="income" type="number" min="0" step={currency === 'TRY' ? 100 : 1} value={ready ? Math.round(income * factor) : ''} disabled={!ready} onChange={(event) => updateProfile('income', event.target.value)} /></div></div><div><label htmlFor="portfolio">INVESTED PORTFOLIO / {currency}</label><div className="profile-input"><span>{symbol}</span><input id="portfolio" type="number" min="0" step={currency === 'TRY' ? 1000 : 100} value={ready ? Math.round(portfolio * factor) : ''} disabled={!ready} onChange={(event) => updateProfile('portfolio', event.target.value)} /></div></div><div className="rate-status" aria-live="polite"><span>{rate ? `1 USD = ₺${rate.rate.toFixed(2)}` : rateStatus}</span>{rate && <small>{usingCache ? 'CACHED FALLBACK' : rate.source} · {rate.date || 'date unavailable'}</small>}{rate && <SourceBadge source={usingCache ? `Cached fallback · ${rate.source}` : rate.source} date={rate.date} fetchedAt={rate.fetchedAt} label="USD/TRY exchange rate" />}<button type="button" onClick={fetchRate}>REFRESH RATE</button></div></section>
    <section className="fire-board panel" aria-labelledby="fire-board-title"><div className="panel-title"><span id="fire-board-title">FIRE PLANNER / {currency} VALUES</span><span className="stamp">4% RULE · 7% RETURN</span></div><div className="fire-content"><div className="expense-block"><div className="eyebrow">MONTHLY EXPENSES / {currency}</div><strong>{output(monthly)}</strong><button className="edit-expenses" type="button" onClick={openEditor}>EDIT EXPENSES</button><div className="surplus-line"><span>MONTHLY SURPLUS / {currency}</span><b className={surplus === null ? '' : surplus >= 0 ? 'up' : 'down'}>{output(surplus)}</b></div></div><div className="fire-results"><div className="result-card"><span className="eyebrow">ANNUAL EXPENSES / {currency}</span><strong>{output(annual)}</strong><span className="result-rule">monthly × 12</span></div><div className="result-card target"><span className="eyebrow">ESTIMATED FIRE TARGET / {currency}</span><strong>{output(target)}</strong><span className="result-rule">annual × 25</span></div><div className="result-card progress-card"><span className="eyebrow">PORTFOLIO PROGRESS</span><strong>{progress === null ? 'UNAVAILABLE' : `${progress.toFixed(0)}%`}</strong><span className="result-rule">{remaining === null ? 'Rate required' : `${output(remaining)} remaining`}</span><div className="progress-track"><i style={{ width: `${progress || 0}%` }} /></div></div><div className="result-card years-card"><span className="eyebrow">ESTIMATED YEARS TO FIRE</span><strong>{years === null ? 'UNAVAILABLE' : years}</strong><span className="result-rule">{years === null ? (ready ? 'Not reachable with current inputs' : 'Rate required') : '7% annual return'}</span></div></div></div>{projection}<p className="formula-note"><b>FORMULA NOTE</b> Values are shown in {currency}. The 4% rule estimates a target of 25× annual expenses; years assume a fixed 7% annual return and annual contributions of surplus × 12.</p></section><div className="status"><span><b>MODEL STATUS</b> · {rateStatus} · 4% withdrawal rule · 7% annual return</span></div>
    {draft && <div className="fire-modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && closeEditor()}><section className="fire-modal" role="dialog" aria-modal="true" aria-labelledby="expense-modal-title"><div className="modal-head"><span id="expense-modal-title">EDIT EXPENSES / {currency}</span><button ref={closeRef} type="button" onClick={closeEditor}>CLOSE ×</button></div><form onSubmit={saveExpenses}><div className="expense-rows">{draft.map((item, index) => <div className="expense-row" key={item.id}><h3 className="expense-heading"><input aria-label={`Edit ${item.name || 'expense'} name`} value={item.name} onChange={(event) => updateDraft(index, { name: event.target.value })} /></h3><div className="expense-prices"><label className="modal-number"><span>{currency}</span><input aria-label={`${item.name || 'Expense'} amount in ${currency}`} type="number" min="0" step={currency === 'TRY' ? 10 : .01} value={ready ? Math.round(item.amount * factor * (currency === 'USD' ? 100 : 1)) / (currency === 'USD' ? 100 : 1) : ''} disabled={!ready} onChange={(event) => updateDraftAmount(index, event.target.value)} /></label></div><button className="delete-expense" type="button" onClick={() => setDraft(draft.filter((_, i) => i !== index))} aria-label={`Delete ${item.name || 'expense'}`}>×</button></div>)}</div><button className="add-expense" type="button" onClick={() => setDraft([...draft, { id: Date.now(), name: 'New expense', amount: 0 }])}>+ ADD EXPENSE</button><div className="modal-total"><span>COMPUTED MONTHLY TOTAL / {currency}</span><strong>{output(ready ? draft.reduce((sum, item) => sum + item.amount, 0) * factor : null)}</strong></div><div className="modal-actions"><button type="button" onClick={closeEditor}>CANCEL</button><button className="save-expenses" type="submit">SAVE EXPENSES</button></div></form></section></div>}
  </main>;
}
