'use client';

import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { Header, formatPrice, movement, percent, SectorDetail, SourceBadge } from './components';

function SnapshotList({ rows, source, fetchedAt }) { return <div className="list">{rows.map((row) => <div key={`${row.ticker}-${row.name}`}><span><b>{row.ticker}</b><span className="mini">{row.name}</span></span><span className={movement(row.oneDay)}>{percent(row.oneDay)} <SourceBadge source={source} fetchedAt={fetchedAt} label={`${row.ticker} market data`} /></span></div>)}</div>; }

function MarketList({ rows, metric, source, fetchedAt, ready }) { return <div className="market-table-wrap"><table className="market-table"><thead><tr><th scope="col"># / MARKET</th><th scope="col">CATEGORY</th><th scope="col">{metric === 'price' ? 'PRICE' : metric === 'oneDay' ? '1D' : '5D'}</th></tr></thead><tbody>{rows.length ? rows.map((row, index) => { const value = row[metric]; const available = Number.isFinite(value); const label = metric === 'price' ? 'price' : metric === 'oneDay' ? '1D' : '5D'; return <tr className={available ? '' : 'unavailable'} key={`${row.ticker}-${row.name}`}><td><span className="market-rank">{String(index + 1).padStart(2, '0')}</span><b>{row.ticker}</b><span className="market-item-name">{row.name}</span></td><td className="market-category">{row.category}</td><td className={metric === 'price' ? '' : available ? movement(value) : ''}>{metric === 'price' ? formatPrice(value) : percent(value)} <SourceBadge source={source} fetchedAt={fetchedAt} label={`${row.name} ${label} market data`} /></td></tr>; }) : <tr><td colSpan="3" className="market-empty">{ready ? 'No matching market items.' : 'Loading market data...'}</td></tr>}</tbody></table></div>; }

export default function Dashboard() {
  const [data, setData] = useState(); const [status, setStatus] = useState('CONNECTING...');
  const [selectedTicker, setSelectedTicker] = useState(); const [marketMetric, setMarketMetric] = useState('price'); const [marketCategory, setMarketCategory] = useState('all'); const [marketSearch, setMarketSearch] = useState(''); const closeRef = useRef();
  const load = async () => { setStatus('FETCHING LIVE PRICES...'); try { const response = await fetch('/api/market-snapshot', { cache: 'no-store' }); const snapshot = await response.json(); if (!response.ok) throw Error(snapshot.error); setData(snapshot); setStatus(`LIVE · ${new Date(snapshot.updatedAt).toLocaleTimeString('en-US')}`); } catch { setStatus('LIVE DATA UNAVAILABLE'); } };
  useEffect(() => { load(); }, []);
  useEffect(() => { if (!selectedTicker) return; closeRef.current?.focus(); const close = (event) => event.key === 'Escape' && setSelectedTicker(); document.addEventListener('keydown', close); document.body.classList.add('modal-open'); return () => { document.removeEventListener('keydown', close); document.body.classList.remove('modal-open'); }; }, [selectedTicker]);
  const rows = data ? [...data.sectors].sort((a, b) => b.score - a.score) : []; const leaders = rows.slice(0, 3); const laggards = rows.slice(-3).reverse(); const positive = rows.filter(({ oneDay }) => oneDay > 0).length; const selectedSector = rows.find(({ ticker }) => ticker === selectedTicker); const provenance = { source: data?.source, fetchedAt: data?.updatedAt }; const query = marketSearch.trim().toLowerCase(); const marketItems = (items, category) => (items || []).filter(({ name = '' }) => name.toLowerCase().includes(query)).map((item) => ({ ...item, category })).sort((a, b) => { const left = Number.isFinite(a[marketMetric]) ? a[marketMetric] : -Infinity; const right = Number.isFinite(b[marketMetric]) ? b[marketMetric] : -Infinity; return right - left; }); const assets = marketItems(data?.assets, 'ASSET CLASS'); const themes = marketItems(data?.themes, 'THEMATIC ETF'); const marketRows = marketCategory === 'assets' ? assets : marketCategory === 'themes' ? themes : [...assets, ...themes].sort((a, b) => { const left = Number.isFinite(a[marketMetric]) ? a[marketMetric] : -Infinity; const right = Number.isFinite(b[marketMetric]) ? b[marketMetric] : -Infinity; return right - left; });
  return <main className="shell"><Header active="DASHBOARD" />
    <section className="panel read-panel"><div className="panel-title">MARKET READ <span className="stamp">LIVE CALCULATION</span></div><div className="market-read">{data ? <><div><div className="eyebrow">BREADTH</div><b>{positive} / 11</b><span className="mini"> sectors positive</span></div><div><div className="eyebrow">LEADERS</div><b className="up">{leaders.map(({ ticker }) => ticker).join(' · ')}</b></div><div><div className="eyebrow">LAGGARDS</div><b className="down">{laggards.map(({ ticker }) => ticker).join(' · ')}</b></div><div><div className="eyebrow">REGIME</div><b className={positive >= 6 ? 'up' : 'down'}>{positive >= 6 ? 'RISK ON' : 'RISK OFF'}</b></div><p className="market-copy">{positive >= 6 ? 'Breadth supports risk appetite.' : 'Breadth is defensive.'} Leadership is in {leaders[0].name}; {laggards[0].name} is the weakest rotation group.</p></> : <p className="market-copy">Loading live market data...</p>}</div></section>
    <div className="grid"><section className="panel"><div className="panel-title">SECTOR ROTATION <span className="stamp">CLICK ANY ROW FOR DETAIL</span></div><div className="table-wrap"><table><thead><tr><th># / ETF</th><th>1D</th><th>5D</th><th>RS vs SPY</th><th>ROTATION SCORE</th></tr></thead><tbody>{rows.map((row, index) => <tr key={row.ticker} className="sector-row" tabIndex="0" role="button" aria-label={`Open details for ${row.name}`} onClick={() => setSelectedTicker(row.ticker)} onKeyDown={(event) => (event.key === 'Enter' || event.key === ' ') && (event.preventDefault(), setSelectedTicker(row.ticker))}><td><span className="rank">{String(index + 1).padStart(2, '0')}</span><span className="ticker">{row.ticker}</span><span className="sector">{row.name}</span></td><td className={movement(row.oneDay)}>{percent(row.oneDay)} <SourceBadge {...provenance} label={`${row.ticker} 1D market data`} /></td><td className={movement(row.fiveDay)}>{percent(row.fiveDay)} <SourceBadge {...provenance} label={`${row.ticker} 5D market data`} /></td><td className={movement(row.rs)}>{percent(row.rs)} <SourceBadge {...provenance} label={`${row.ticker} relative strength market data`} /></td><td className={`score ${movement(row.score - 50)}`}>{row.score} <SourceBadge {...provenance} label={`${row.ticker} rotation score inputs`} /><span className="bar"><b style={{ width: `${row.score}%` }} /></span></td></tr>)}</tbody></table></div></section><aside className="side"><section className="panel"><div className="panel-title">ROTATION LEADERS</div><SnapshotList rows={leaders} {...provenance} /></section><section className="panel"><div className="panel-title">ROTATION LAGGARDS</div><SnapshotList rows={laggards} {...provenance} /></section></aside></div>
    <section className="panel market-board"><div className="panel-title"><span>MARKET SNAPSHOT</span><span className="stamp">SORTED BY SELECTED METRIC</span></div><div className="market-controls"><label className="market-search"><span className="sr-only">Search market items by name</span><span aria-hidden="true">⌕</span><input type="search" value={marketSearch} onChange={(event) => setMarketSearch(event.target.value)} placeholder="Search by name" /></label><div className="market-periods" role="tablist" aria-label="Market sort metric"><span className="sort-label">SORT</span>{[['price', 'PRICE'], ['oneDay', '1D'], ['fiveDay', '5D']].map(([metric, label]) => <button key={metric} type="button" role="tab" aria-selected={marketMetric === metric} className={marketMetric === metric ? 'active' : ''} onClick={() => setMarketMetric(metric)}>{label}</button>)}</div></div><div className="market-filters" role="tablist" aria-label="Market category"><button type="button" role="tab" aria-selected={marketCategory === 'all'} className={marketCategory === 'all' ? 'active' : ''} onClick={() => setMarketCategory('all')}>ALL <span>{assets.length + themes.length}</span></button><button type="button" role="tab" aria-selected={marketCategory === 'assets'} className={marketCategory === 'assets' ? 'active' : ''} onClick={() => setMarketCategory('assets')}>ASSET CLASS <span>{assets.length}</span></button><button type="button" role="tab" aria-selected={marketCategory === 'themes'} className={marketCategory === 'themes' ? 'active' : ''} onClick={() => setMarketCategory('themes')}>THEMATIC ETFs <span>{themes.length}</span></button></div><MarketList rows={marketRows} metric={marketMetric} ready={Boolean(data)} {...provenance} /></section>
    <div className="status"><span><b className="up">●</b> LIVE MARKET PRICES</span><span>{status}</span><button onClick={load}>REFRESH</button><Link href="/data">SOURCE NOTES →</Link></div><p className="foot">ROTATION SCORE = 1D + 5D MOMENTUM + RELATIVE STRENGTH. NO SYNTHETIC MARKET VALUES.</p>
    {selectedTicker && <div className="modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && setSelectedTicker()}><section className="sector-modal" role="dialog" aria-modal="true" aria-labelledby="sector-modal-title"><div className="modal-head"><span id="sector-modal-title">SECTOR DETAIL</span><button ref={closeRef} onClick={() => setSelectedTicker()} aria-label="Close">CLOSE ×</button></div><SectorDetail sector={selectedSector} sectors={rows} onSelect={setSelectedTicker} {...provenance} /></section></div>}
  </main>;
}
