'use client';

import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { Header, movement, percent, SectorDetail } from './components';

function SnapshotList({ rows }) { return <div className="list">{rows.map((row) => <div key={row.ticker}><span><b>{row.ticker}</b><span className="mini">{row.name}</span></span><span className={movement(row.oneDay)}>{percent(row.oneDay)}</span></div>)}</div>; }

export default function Dashboard() {
  const [data, setData] = useState(); const [status, setStatus] = useState('CONNECTING...');
  const [selectedTicker, setSelectedTicker] = useState(); const closeRef = useRef();
  const load = async () => { setStatus('FETCHING LIVE PRICES...'); try { const response = await fetch('/api/market-snapshot', { cache: 'no-store' }); const snapshot = await response.json(); if (!response.ok) throw Error(snapshot.error); setData(snapshot); setStatus(`LIVE · ${new Date(snapshot.updatedAt).toLocaleTimeString('en-US')}`); } catch { setStatus('LIVE DATA UNAVAILABLE'); } };
  useEffect(() => { load(); }, []);
  useEffect(() => { if (!selectedTicker) return; closeRef.current?.focus(); const close = (event) => event.key === 'Escape' && setSelectedTicker(); document.addEventListener('keydown', close); document.body.classList.add('modal-open'); return () => { document.removeEventListener('keydown', close); document.body.classList.remove('modal-open'); }; }, [selectedTicker]);
  const rows = data ? [...data.sectors].sort((a, b) => b.score - a.score) : []; const leaders = rows.slice(0, 3); const laggards = rows.slice(-3).reverse(); const positive = rows.filter(({ oneDay }) => oneDay > 0).length; const selectedSector = rows.find(({ ticker }) => ticker === selectedTicker);
  return <main className="shell"><Header active="DASHBOARD" />
    <section className="panel read-panel"><div className="panel-title">MARKET READ <span className="stamp">LIVE CALCULATION</span></div><div className="market-read">{data ? <><div><div className="eyebrow">BREADTH</div><b>{positive} / 11</b><span className="mini"> sectors positive</span></div><div><div className="eyebrow">LEADERS</div><b className="up">{leaders.map(({ ticker }) => ticker).join(' · ')}</b></div><div><div className="eyebrow">LAGGARDS</div><b className="down">{laggards.map(({ ticker }) => ticker).join(' · ')}</b></div><div><div className="eyebrow">REGIME</div><b className={positive >= 6 ? 'up' : 'down'}>{positive >= 6 ? 'RISK ON' : 'RISK OFF'}</b></div><p className="market-copy">{positive >= 6 ? 'Breadth supports risk appetite.' : 'Breadth is defensive.'} Leadership is in {leaders[0].name}; {laggards[0].name} is the weakest rotation group.</p></> : <p className="market-copy">Loading live market data...</p>}</div></section>
    <div className="grid"><section className="panel"><div className="panel-title">SECTOR ROTATION <span className="stamp">CLICK ANY ROW FOR DETAIL</span></div><div className="table-wrap"><table><thead><tr><th># / ETF</th><th>1D</th><th>5D</th><th>RS vs SPY</th><th>ROTATION SCORE</th></tr></thead><tbody>{rows.map((row, index) => <tr key={row.ticker} className="sector-row" tabIndex="0" role="button" aria-label={`Open details for ${row.name}`} onClick={() => setSelectedTicker(row.ticker)} onKeyDown={(event) => (event.key === 'Enter' || event.key === ' ') && (event.preventDefault(), setSelectedTicker(row.ticker))}><td><span className="rank">{String(index + 1).padStart(2, '0')}</span><span className="ticker">{row.ticker}</span><span className="sector">{row.name}</span></td><td className={movement(row.oneDay)}>{percent(row.oneDay)}</td><td className={movement(row.fiveDay)}>{percent(row.fiveDay)}</td><td className={movement(row.rs)}>{percent(row.rs)}</td><td className={`score ${movement(row.score - 50)}`}>{row.score}<span className="bar"><b style={{ width: `${row.score}%` }} /></span></td></tr>)}</tbody></table></div></section><aside className="side"><section className="panel"><div className="panel-title">ROTATION LEADERS</div><SnapshotList rows={leaders} /></section><section className="panel"><div className="panel-title">ROTATION LAGGARDS</div><SnapshotList rows={laggards} /></section></aside></div>
    <div className="bottom">{[['ASSET-CLASS PERFORMANCE', data?.assets], ['THEMATIC ETF PERFORMANCE', data?.themes]].map(([title, rows]) => <section className="panel" key={title}><div className="panel-title">{title} <span className="stamp">LIVE 1D</span></div><SnapshotList rows={rows || []} /></section>)}</div>
    <div className="status"><span><b className="up">●</b> LIVE MARKET PRICES</span><span>{status}</span><button onClick={load}>REFRESH</button><Link href="/data">SOURCE NOTES →</Link></div><p className="foot">ROTATION SCORE = 1D + 5D MOMENTUM + RELATIVE STRENGTH. NO SYNTHETIC MARKET VALUES.</p>
    {selectedTicker && <div className="modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && setSelectedTicker()}><section className="sector-modal" role="dialog" aria-modal="true" aria-labelledby="sector-modal-title"><div className="modal-head"><span id="sector-modal-title">SECTOR DETAIL</span><button ref={closeRef} onClick={() => setSelectedTicker()} aria-label="Close">CLOSE ×</button></div><SectorDetail sector={selectedSector} sectors={rows} onSelect={setSelectedTicker} /></section></div>}
  </main>;
}
